server:
  port: 9192

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    username: root
    password: system
    url: jdbc:mysql://localhost:3306/foodkart_database
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      format_sql: true