server:
  port: 9192
  tomcat:
    max-http-form-post-size: 10MB
    max-http-header-size: 64KB


#  spring:
#    servlet:
#      multipart:
#        max-file-size: 10MB
#        max-request-size: 10MB
#
#  server:
#    tomcat:
#      max-http-form-post-size: 10MB
#    max-http-header-size: 64KB


#  spring.mail.host=smtp.gmail.com
#  spring.mail.port=587
#  spring.mail.username=your-email@gmail.com
#  spring.mail.password=your-app-password
#  spring.mail.properties.mail.smtp.auth=true
#  spring.mail.properties.mail.smtp.starttls.enable=true


spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: foodkart95@gmail.com
    password: vtar xele arnm cuii
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  datasource:
    username: root
    password: bhunesh@123
    url: jdbc:mysql://localhost:3306/foodkart_database
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      format_sql: true

    properties:
      hibernate:
        dialect=org:
          hibernate:
            dialect:
              MySQL8Dialect: org.hibernate.dialect.MySQL8Dialect